### ISSUE TITLE
概要の作成

### ISSUE THREAD

**Issue by ttakuya** [ttakuya/PythonCalculusBook#2]
企画会議用に概要を作成します。たとえば「Pythonで学ぶ統計解析」の概要は以下のような感じです。

初学者向けのプログラミング学習や機械学習を利用する用途でPythonは注目を浴びています。本書は、Pythonの入門書を読み終えた方を対象に、次のステップとして統計解析を解説します。統計解析はデータサイエンス分野に入門する上で基礎となる重要な知識です。Pythonを用いて統計解析を解説する利点は2つあります。1つ目にPythonはNumpyやScipy、pandasなどの統計解析において有用なライブラリをたくさん提供しています。面倒な計算もかんたんなコードで確認できます。2つ目はプログラミング言語を用いることで、統計解析の概念を視覚的に理解できることです。データの集合、尤度の推定、確率分布などはPythonの描画ライブラリによって静的な誌面で学習するよりも理解しやすくなるでしょう。本書では統計検定2級程度の知識を学習できることを目的とします。

**Comment by ttakuya** [comment]
こちらのissueに続けていただくのでOKです。

**Comment by iguchik001** [comment]
お世話になります。概要の作成について承知致しました。
「はじめに」の章と、目次の作成のために谷合さんの原稿を参考にさせていただけないでしょうか？
よろしくお願い致します。

**Comment by ttakuya** [comment]
以下にアップしました。不明な点があればご連絡ください。

https://github.com/ttakuya/PythonCalculusBook/blob/master/Archive/main.pdf

**Comment by iguchik001** [comment]
谷合さんの原稿のアップロードありがとうございます。
参考にさせていただきます。私もJupyter notebookで原稿を作成しようと思います。
以下に概要を記します。

**Comment by iguchik001** [comment]
書きやすく読みやすいプログラミング言語であるPythonは初学者のプログラミング学習に適しているとともに、豊富な計算ライブラリが簡単に使えるため科学計算、データサイエンスにおいて注目を浴びています。本書ではPythonの入門書を読み終え、科学計算、データサイエンスなどでPythonを活用したい方に微分積分を解説します。微分積分は科学計算、データサイエンスに入門する上で基礎となる重要な知識であり、本書を通してPythonを使いながら微分積分のエッセンスを学びます。具体的には、Pyhonでの式計算を学び、関数の極限値を求めたり、導関数を計算したり、関数の積分を実行したりします。Pythonの描画ライブラリで関数を描くことで微分積分をより直感的に理解することがでます。本書の後半では科学計算の例として微分方程式を解き、データサイエンスの例として機械学習の最適化における最小二乗法について学習します。

**Comment by ttakuya** [comment]
承知しました！こちらOKです。
個人的にもしっかり学び直したいので楽しみです。解説にPythonのプロットと計算はうまく利用できると思います。

それではこちらはクローズします。
